"""empty message

Revision ID: 40783188b76c
Revises: 8e1699bca54b
Create Date: 2019-12-31 17:48:57.128583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40783188b76c'
down_revision = '8e1699bca54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
