"""empty message

Revision ID: 997c42df0be7
Revises: 75a9559b868d
Create Date: 2019-12-31 13:46:29.868852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997c42df0be7'
down_revision = '75a9559b868d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
